custom messages ( scoopControl and wheelData)
stateSpaceRobotics/robot2017 pull request #17
Opened 2016-09-28 03:39 UTC by bgrayd

Custom messages for wheelData (such as for the current speed of the wheels) and scoopControl (worded vaguely so it can be used for either speed or angle)

2016-09-28 15:40 UTC, daftpwner requested changes
Needs names that explicitly define the purpose of the variables.  Header's should also be present as this is time and frame oriented information.

2016-09-28 15:40 UTC, daftpwner commented on cr17/msg/scoopControl.msg
> +float64 arm
This variable needs a more meaningful name to indicate it is an angular measurement.

2016-09-28 15:40 UTC, daftpwner commented on cr17/msg/scoopControl.msg
> +float64 scoop
More meaningful name.

2016-09-28 15:40 UTC, daftpwner commented on cr17/msg/scoopControl.msg
> +
There should be a header to hold timestamp and frame id information to show when and where these angles have meaning.

2016-09-28 15:40 UTC, daftpwner commented on cr17/msg/wheelData.msg
> +
Needs a header for the timestamp.

2016-09-28 15:40 UTC, daftpwner commented on cr17/msg/wheelData.msg
> +float64 backRight
More meaningful names.  Is this velocity in encoder pulses or m/s?

2016-09-29 05:44 UTC, bgrayd commented
I believe I have addressed the first comments with commit 4e61db5b8cca7f756dd0cb86cf04e22ad268d64

2016-09-29 21:02 UTC, JacobAMason approved these changes
Billy fixed all this, so I'm going to see if this closes the review.

2016-09-29 21:02 UTC, JacobAMason commented
Spoiler alert: it doesn't. @daftpwner will have to close it.

2016-09-29 23:35 UTC, daftpwner approved these changes

2016-09-29 23:35 UTC, merged