Basic navigator unit tests
stateSpaceRobotics/robot2017 pull request #28
Opened 2017-01-26 19:36 UTC by bgrayd

These are unit tests for the basic functionality of the navigator and also works as an example unit test for others to use when making a new unit test.  It also includes moving some of the functions that do not need to be part of the navigator node class outside of the class, so that they can be tested without ROS.

2017-03-10 03:14 UTC, JacobAMason requested changes

2017-03-10 03:14 UTC, JacobAMason commented on cr17/test/test_navigator.py
> +    def test_at_goal(self):
This test should include an assertion to test the tolerance feature of this function.

2017-03-10 03:14 UTC, JacobAMason commented on cr17/nodes/cr17/navigator.py
> +    return [d_x, d_y]
Is this meant to be a list/mutable? Would it be better formulated as a tuple?

2017-03-10 03:14 UTC, JacobAMason commented on cr17/nodes/cr17/navigator.py
> +    rep_force = [0, 0]
list/tuple

2017-03-10 03:14 UTC, JacobAMason commented on cr17/test/test_navigator.py
> +        self.assertListAlmostEqual([-0.929,-0.929], navigator.calc_goal_force(goalBackRight, robotPose), 3)
list/tuple

2017-03-10 03:14 UTC, JacobAMason commented on cr17/test/test_navigator.py
> +        obstacle4 = [-0.4,0]
list/tuple

2017-03-10 03:14 UTC, JacobAMason commented on cr17/test/test_navigator.py
> +        self.assertListAlmostEqual([0.22, 0], navigator.calc_repulsive_force([obstacle4, obstacle4],robotPose))
list/tuple

2017-03-10 20:25 UTC, bgrayd commented on cr17/test/test_navigator.py
> +    def test_at_goal(self):
I believe this was fixed in 79e09e4a7334979cb3e82fb2bf824e29fd1342ad

2017-03-10 20:25 UTC, bgrayd commented on cr17/test/test_navigator.py
> +        self.assertListAlmostEqual([-0.929,-0.929], navigator.calc_goal_force(goalBackRight, robotPose), 3)
Fixed in 2b4de4372834138b7cde16f7b3bd395bf3d75540

2017-03-10 20:25 UTC, bgrayd commented on cr17/test/test_navigator.py
> +        obstacle4 = [-0.4,0]
Fixed in 2b4de4372834138b7cde16f7b3bd395bf3d75540

2017-03-10 20:25 UTC, bgrayd commented on cr17/test/test_navigator.py
> +        self.assertListAlmostEqual([0.22, 0], navigator.calc_repulsive_force([obstacle4, obstacle4],robotPose))
Fixed in 2b4de4372834138b7cde16f7b3bd395bf3d75540

2017-03-10 20:25 UTC, bgrayd commented on cr17/nodes/cr17/navigator.py
> +    return [d_x, d_y]
There was a place in a different function where it normalized the vector, but that was changed to use tuples. Changed in 2b4de4372834138b7cde16f7b3bd395bf3d75540

2017-03-10 20:26 UTC, bgrayd commented on cr17/nodes/cr17/navigator.py
> +    rep_force = [0, 0]
Fixed in 2b4de4372834138b7cde16f7b3bd395bf3d75540

2017-03-12 23:53 UTC, JacobAMason approved these changes

2017-03-12 23:53 UTC, JacobAMason commented on cr17/nodes/cr17/navigator.py
> +        rep_force = (rep_force[0]+d_x, rep_force[1]+d_y)
might want to leave this as a list and then `return tuple(rep_force)`

2017-03-12 23:54 UTC, JacobAMason commented on cr17/test/test_navigator.py
> +    def test_at_goal(self):
It is indeed

2017-03-18 03:33 UTC, merged