Feature/teleop
stateSpaceRobotics/robot2017 pull request #32
Opened 2017-02-10 05:13 UTC by bgrayd

I have started the teleop node, but it still needs the service calls to services that haven't been written yet.  It also needs to do the arm control, but I am not sure how defined that is yet.  This should also be able to be used in gazebo.

2017-02-15 01:19 UTC, JacobAMason requested changes
startTeleop and endTeleop are camel case functions and all your other functions are underscored.

2017-02-15 01:19 UTC, JacobAMason commented on cr17/nodes/cr17/joystick_controller.py
> +        #TODO: call the serives from navigator, scoop_controller, and the HLSC
"serives" ?

2017-02-15 01:19 UTC, JacobAMason commented on cr17/nodes/cr17/joystick_controller.py
> +        #TODO: call the serives from navigator, scoop_controller, and the HLSC
"serives"

2017-02-15 01:19 UTC, JacobAMason commented on cr17/nodes/cr17/joystick_controller.py
> +    def _exit_handler(self):
Is this method ever used?

2017-03-03 19:35 UTC, bgrayd commented
I had not seen the comment about the function names, that has been fixed.  I also added in the service calls.

2017-03-13 18:56 UTC, JacobAMason approved these changes

2017-03-20 17:16 UTC, merged