feature/scoop-controller
stateSpaceRobotics/robot2017 pull request #34
Opened 2017-02-24 04:04 UTC by nathantfrank

Scoop Controller Implementation

2017-03-03 19:01 UTC, bgrayd requested changes

2017-03-03 19:01 UTC, bgrayd commented on cr17/nodes/cr17/scoop_controller.py
> +ARM_STATE_TOPIC = rospy.get_param('topics/scoop_state_cmds')
This should be added to the parameter file topics.yaml

2017-03-03 19:01 UTC, bgrayd commented on cr17/nodes/cr17/scoop_controller.py
> +ARM_GOAL_TOPIC = rospy.get_param('topics/scoop_cmds')
This should be added to the parameter file topics.yaml

2017-03-03 19:24 UTC, bgrayd submitted a review, later dismissed

2017-03-03 19:24 UTC, bgrayd commented on cr17/nodes/cr17/scoop_controller.py
> +        req.acknowledged = True
This causes an error.  The req variable is just the request part of the service call.  For setting the output of this service, autonomousActiveResponse should be instantiated and used.

2017-03-03 19:24 UTC, bgrayd commented on cr17/nodes/cr17/scoop_controller.py
> +from cr17.srv import autonomousActive
Should also import autonomousActiveResponse from the services as well

2017-04-08 15:13 UTC, JacobAMason commented
@bgrayd Can you give this an updated review so we can merge it?

2017-04-08 20:19 UTC, bgrayd requested changes

2017-04-08 20:19 UTC, bgrayd commented on cr17/nodes/cr17/high_level_state_controller.py
> -from cr17.msg import scoopControl
Why is this being removed?

2017-04-08 20:19 UTC, bgrayd commented on cr17/nodes/cr17/high_level_state_controller.py
> -from cr17.srv import autonomousActive, autonomousActiveResponse
I think something might be going wrong with the merge on this file...

2017-04-08 20:19 UTC, bgrayd commented on cr17/nodes/cr17/high_level_state_controller.py
> +        self.teleopButton_prev = 0
Yea, this is not the correct high_level_state_controller, this merge will wipe lots of changes to it

2017-04-08 22:47 UTC, nathantfrank commented
@bgrayd the branch should be correctly up to date with develop now.

2017-04-09 17:53 UTC, bgrayd approved these changes
LGTM

2017-04-09 19:38 UTC, merged